import type { ServiceCategory, User, ServiceRequest, JobPost } from './types';
import { WrenchScrewdriverIcon, BoltIcon, PaintBrushIcon, ShieldCheckIcon, TruckIcon, ComputerDesktopIcon } from './components/icons';

export const serviceCategories: ServiceCategory[] = [
  { name: 'Encanador', icon: WrenchScrewdriverIcon },
  { name: 'Eletricista', icon: BoltIcon },
  { name: 'Pintor', icon: PaintBrushIcon },
  { name: 'Segurança', icon: ShieldCheckIcon },
  { name: 'Fretes', icon: TruckIcon },
  { name: 'Técnico de TI', icon: ComputerDesktopIcon },
];

export const users: User[] = [
  // --- ADMIN ---
  { 
    id: 3, 
    name: 'Admin', 
    email: 'admin@tiao.com', 
    password: 'admin', 
    role: 'admin', 
    isProfileComplete: true,
    phone: 'N/A',
    location: 'N/A',
  },
  // --- CLIENTS (10 total) ---
  { 
    id: 1, 
    name: 'Ana Cliente', 
    email: 'cliente@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '21987654321',
    location: 'Leblon, Rio de Janeiro',
  },
  { 
    id: 6, 
    name: 'Bruno Cliente', 
    email: 'bruno@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '21911223344',
    location: 'Ipanema, Rio de Janeiro',
  },
  { 
    id: 7, 
    name: 'Carla Souza', 
    email: 'carla@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '11988887777',
    location: 'Moema, São Paulo',
  },
  { 
    id: 8, 
    name: 'Lucas Pereira', 
    email: 'lucas@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '31977776666',
    location: 'Lourdes, Belo Horizonte',
  },
  { 
    id: 9, 
    name: 'Juliana Costa', 
    email: 'juliana@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '71966665555',
    location: 'Barra, Salvador',
  },
  { 
    id: 10, 
    name: 'Fernando Martins', 
    email: 'fernando@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '51955554444',
    location: 'Moinhos de Vento, Porto Alegre',
  },
  { 
    id: 11, 
    name: 'Beatriz Almeida', 
    email: 'beatriz@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '41944443333',
    location: 'Batel, Curitiba',
  },
  { 
    id: 12, 
    name: 'Ricardo Rocha', 
    email: 'ricardo@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '81933332222',
    location: 'Boa Viagem, Recife',
  },
  { 
    id: 13, 
    name: 'Camila Lima', 
    email: 'camila@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '85922221111',
    location: 'Meireles, Fortaleza',
  },
  { 
    id: 14, 
    name: 'Gustavo Barbosa', 
    email: 'gustavo@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '61911110000',
    location: 'Asa Sul, Brasília',
  },
  // --- PROFESSIONALS (2+ per category) ---
  // Encanadores
  { 
    id: 2, 
    name: 'Roberto Carlos', 
    email: 'profissional@tiao.com', 
    password: '123', 
    role: 'professional', 
    status: 'approved', 
    isProfileComplete: true,
    phone: '11912345678',
    location: 'Copacabana, Rio de Janeiro',
    service: 'Encanador',
    cpfCnpj: '123.456.789-00',
    bio: 'Mais de 20 anos de experiência em reparos hidráulicos residenciais e comerciais. Rápido, eficiente e confiável.',
    imageUrl: 'https://picsum.photos/seed/roberto/300/300',
    rating: 4.9,
    reviewsCount: 128,
    reviews: [
      { id: 1, author: 'Ana', rating: 5, comment: 'Resolveu meu vazamento em 10 minutos! Incrível.' },
      { id: 2, author: 'Bruno', rating: 5, comment: 'Muito profissional e educado. Recomendo.' },
    ],
    pricing: { description: 'A partir de R$ 150,00' },
    availability: { 'Seg-Sex': '08:00 - 18:00', 'Sábado': '09:00 - 13:00' },
  },
  { 
    id: 15, 
    name: 'Sérgio Mendes', 
    email: 'sergio@tiao.com', 
    password: '123', 
    role: 'professional', 
    status: 'approved', 
    isProfileComplete: true,
    phone: '21988776655',
    location: 'Tijuca, Rio de Janeiro',
    service: 'Encanador',
    cpfCnpj: '222.333.444-55',
    bio: 'Especialista em detecção de vazamentos com equipamentos de ultrassom. Serviço limpo e sem quebra-quebra desnecessário.',
    imageUrl: 'https://picsum.photos/seed/sergio/300/300',
    rating: 4.8,
    reviewsCount: 76,
    pricing: { description: 'Orçamento a combinar' },
  },
  // Eletricistas
  {
    id: 4,
    name: 'Mariana Silva',
    service: 'Eletricista',
    email: 'mariana@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '11987654321',
    location: 'Vila Madalena, São Paulo',
    cpfCnpj: '098.765.432-11',
    rating: 4.8,
    reviewsCount: 95,
    bio: 'Especialista em instalações elétricas e reparos de curto-circuito. Segurança em primeiro lugar.',
    imageUrl: 'https://picsum.photos/seed/mariana/300/300',
    reviews: [
        { id: 1, author: 'Carlos', rating: 5, comment: 'Trocou toda a fiação do meu apartamento com perfeição.' },
        { id: 2, author: 'Julia', rating: 4, comment: 'Serviço bem feito, mas demorou um pouco para chegar.' },
    ],
    pricing: { description: 'R$ 90,00 por hora' },
    availability: { 'Seg-Sex': '09:00 - 17:00' },
  },
  {
    id: 16,
    name: 'Fábio Lima',
    service: 'Eletricista',
    email: 'fabio@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '11976543210',
    location: 'Tatuapé, São Paulo',
    cpfCnpj: '333.444.555-66',
    rating: 4.9,
    reviewsCount: 112,
    bio: 'Instalação de lustres, ventiladores de teto e quadros de luz. Atendo emergências 24h.',
    imageUrl: 'https://picsum.photos/seed/fabio/300/300',
    pricing: { description: 'Serviços a partir de R$ 120,00' },
  },
  // Pintores
  {
    id: 5,
    name: 'Pedro Pendente',
    email: 'pedro@tiao.com',
    password: '123',
    role: 'professional',
    status: 'pending',
    isProfileComplete: false,
    phone: '31999998888',
    location: 'Savassi, Belo Horizonte',
    service: 'Pintor',
    cpfCnpj: '111.222.333-44',
  },
  {
    id: 17,
    name: 'Jorge Benício',
    service: 'Pintor',
    email: 'jorge@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '31988887777',
    location: 'Centro, Belo Horizonte',
    cpfCnpj: '444.555.666-77',
    rating: 4.7,
    reviewsCount: 68,
    bio: 'Pintura residencial e comercial, texturas e grafiato. Acabamento de primeira qualidade e limpeza garantida.',
    imageUrl: 'https://picsum.photos/seed/jorge/300/300',
    pricing: { description: 'Orçamento grátis por m²' },
  },
  {
    id: 18,
    name: 'Vanessa da Mata',
    service: 'Pintor',
    email: 'vanessa@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '21977778888',
    location: 'Barra da Tijuca, Rio de Janeiro',
    cpfCnpj: '555.666.777-88',
    rating: 5.0,
    reviewsCount: 45,
    bio: 'Pintura decorativa e artística para ambientes internos. Transformo sua parede em uma obra de arte.',
    imageUrl: 'https://picsum.photos/seed/vanessa/300/300',
    pricing: { description: 'Projetos a partir de R$ 500,00' },
  },
  // Segurança
  {
    id: 19,
    name: 'Thiago Segurança',
    service: 'Segurança',
    email: 'thiago@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '11966665555',
    location: 'Morumbi, São Paulo',
    cpfCnpj: '666.777.888-99',
    rating: 4.9,
    reviewsCount: 88,
    bio: 'Instalação de câmeras de segurança (CFTV), alarmes e cercas elétricas. Monitore sua casa ou empresa pelo celular.',
    imageUrl: 'https://picsum.photos/seed/thiago/300/300',
    pricing: { description: 'Pacotes de instalação a combinar' },
  },
  {
    id: 20,
    name: 'Paula Toller',
    service: 'Segurança',
    email: 'paula@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '21955554444',
    location: 'Botafogo, Rio de Janeiro',
    cpfCnpj: '777.888.999-00',
    rating: 4.8,
    reviewsCount: 52,
    bio: 'Consultoria de segurança residencial e instalação de fechaduras digitais e portões eletrônicos.',
    imageUrl: 'https://picsum.photos/seed/paula/300/300',
    pricing: { description: 'Consulta técnica: R$ 250,00' },
  },
  // Fretes
  {
    id: 21,
    name: 'Marcos Freteiro',
    service: 'Fretes',
    email: 'marcos@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '11944443333',
    location: 'Toda Grande São Paulo',
    cpfCnpj: '888.999.000-11',
    rating: 4.7,
    reviewsCount: 150,
    bio: 'Pequenos fretes e mudanças com Kombi. Responsabilidade e cuidado com seus pertences.',
    imageUrl: 'https://picsum.photos/seed/marcos/300/300',
    pricing: { description: 'Fretes a partir de R$ 80,00' },
  },
  {
    id: 22,
    name: 'Renata Mudanças',
    service: 'Fretes',
    email: 'renata@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '41933332222',
    location: 'Água Verde, Curitiba',
    cpfCnpj: '999.000.111-22',
    rating: 4.9,
    reviewsCount: 89,
    bio: 'Mudanças residenciais completas com caminhão baú. Equipe para embalagem, desmontagem e montagem de móveis.',
    imageUrl: 'https://picsum.photos/seed/renata/300/300',
    pricing: { description: 'Orçamento sem compromisso' },
  },
  // Técnico de TI
  {
    id: 23,
    name: 'Silvio Meira',
    service: 'Técnico de TI',
    email: 'silvio@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '81922221111',
    location: 'Recife Antigo, Recife',
    cpfCnpj: '000.111.222-33',
    rating: 5.0,
    reviewsCount: 210,
    bio: 'Manutenção de computadores e notebooks, remoção de vírus, formatação e instalação de programas. Atendimento em domicílio.',
    imageUrl: 'https://picsum.photos/seed/silvio/300/300',
    pricing: { description: 'Visita técnica: R$ 100,00' },
  },
  {
    id: 24,
    name: 'Débora TI',
    service: 'Técnico de TI',
    email: 'debora@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '61911112222',
    location: 'Asa Norte, Brasília',
    cpfCnpj: '111.222.333-45',
    rating: 4.9,
    reviewsCount: 98,
    bio: 'Configuração de redes Wi-Fi, roteadores e repetidores de sinal. Deixe sua internet voando!',
    imageUrl: 'https://picsum.photos/seed/debora/300/300',
    pricing: { description: 'Configuração de rede: R$ 180,00' },
  },
];

export const serviceRequests: ServiceRequest[] = [
    {
        id: 101,
        clientId: 1,
        professionalId: 2,
        serviceName: 'Encanador',
        status: 'completed',
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
    },
    {
        id: 102,
        clientId: 6,
        professionalId: 2,
        serviceName: 'Encanador',
        status: 'accepted',
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    },
    {
        id: 103,
        clientId: 1,
        professionalId: 4,
        serviceName: 'Eletricista',
        status: 'pending',
        createdAt: new Date().toISOString(), // today
    },
    {
        id: 104,
        clientId: 6,
        professionalId: 2,
        serviceName: 'Encanador',
        status: 'pending',
        createdAt: new Date().toISOString(), // today
    }
];

export const jobPosts: JobPost[] = [
    {
        id: 201,
        clientId: 1, // Ana Cliente
        serviceCategory: 'Eletricista',
        description: 'Preciso instalar 3 novas tomadas na minha sala e trocar o disjuntor do chuveiro. Urgente!',
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    },
    {
        id: 202,
        clientId: 6, // Bruno Cliente
        serviceCategory: 'Encanador',
        description: 'Vazamento pequeno debaixo da pia da cozinha. Acredito que seja o sifão.',
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    },
    {
        id: 203,
        clientId: 7, // Carla Souza
        serviceCategory: 'Pintor',
        description: 'Quero pintar meu quarto de 12m². A cor é um cinza claro, já tenho a tinta.',
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    }
];
