import type { ServiceCategory, User, ServiceRequest, JobPost, ChatMessage, FormField } from './types';
import { 
  WrenchScrewdriverIcon, BoltIcon, PaintBrushIcon, ShieldCheckIcon, TruckIcon, ComputerDesktopIcon,
  CogIcon, BeakerIcon, FireIcon, HomeModernIcon, KeyIcon, PaintBucketIcon, TvIcon, WifiIcon, UsersIcon as DiaristaIcon, BuildingStorefrontIcon
} from './components/icons';

export const serviceCategories: ServiceCategory[] = [
  { name: 'Encanador', icon: WrenchScrewdriverIcon },
  { name: 'Eletricista', icon: BoltIcon },
  { name: 'Pintor', icon: PaintBrushIcon },
  { name: 'Segurança', icon: ShieldCheckIcon },
  { name: 'Fretes', icon: TruckIcon },
  { name: 'Técnico de TI', icon: ComputerDesktopIcon },
  { name: 'Marceneiro', icon: CogIcon },
  { name: 'Jardineiro', icon: BeakerIcon },
  { name: 'Montador de Móveis', icon: HomeModernIcon },
  { name: 'Dedetizador', icon: FireIcon },
  { name: 'Vidraceiro', icon: BuildingStorefrontIcon },
  { name: 'Gesseiro', icon: PaintBucketIcon },
  { name: 'Ar Condicionado', icon: WifiIcon },
  { name: 'Pedreiro', icon: TvIcon },
  { name: 'Diarista', icon: DiaristaIcon },
  { name: 'Chaveiro', icon: KeyIcon },
];

export const users: User[] = [
  // --- ADMIN ---
  { 
    id: 3, 
    name: 'Admin', 
    email: 'admin@tiao.com', 
    password: 'admin', 
    role: 'admin', 
    isProfileComplete: true,
    phone: 'N/A',
    street: 'N/A', neighborhood: 'N/A', city: 'N/A', state: 'N/A', regionId: 0,
  },
  // --- CLIENTS (10 total) ---
  { 
    id: 1, 
    name: 'Ana Cliente', 
    nickname: 'Aninha',
    email: 'cliente@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '21987654321',
    street: 'Av. Vieira Souto, 123', neighborhood: 'Leblon', city: 'Rio de Janeiro', state: 'RJ', regionId: 1,
    bio: 'Adoro viajar e experimentar novas comidas. Estou sempre em busca de profissionais confiáveis para pequenos reparos em casa.'
  },
  { 
    id: 6, 
    name: 'Bruno Cliente', 
    email: 'bruno@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '21911223344',
    street: 'Rua Prudente de Morais, 456', neighborhood: 'Ipanema', city: 'Rio de Janeiro', state: 'RJ', regionId: 1,
  },
  { 
    id: 7, 
    name: 'Carla Souza', 
    email: 'carla@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '11988887777',
    street: 'Av. Ibirapuera, 789', neighborhood: 'Moema', city: 'São Paulo', state: 'SP', regionId: 2,
  },
  { 
    id: 8, 
    name: 'Lucas Pereira', 
    email: 'lucas@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '31977776666',
    street: 'Rua da Bahia, 101', neighborhood: 'Lourdes', city: 'Belo Horizonte', state: 'MG', regionId: 3,
  },
  { 
    id: 9, 
    name: 'Juliana Costa', 
    email: 'juliana@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '71966665555',
    street: 'Av. Oceânica, 202', neighborhood: 'Barra', city: 'Salvador', state: 'BA', regionId: 4,
  },
  { 
    id: 10, 
    name: 'Fernando Martins', 
    email: 'fernando@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '51955554444',
    street: 'Rua Padre Chagas, 303', neighborhood: 'Moinhos de Vento', city: 'Porto Alegre', state: 'RS', regionId: 5,
  },
  { 
    id: 11, 
    name: 'Beatriz Almeida', 
    email: 'beatriz@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '41944443333',
    street: 'Al. Dr. Carlos de Carvalho, 404', neighborhood: 'Batel', city: 'Curitiba', state: 'PR', regionId: 6,
  },
  { 
    id: 12, 
    name: 'Ricardo Rocha', 
    email: 'ricardo@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '81933332222',
    street: 'Av. Boa Viagem, 505', neighborhood: 'Boa Viagem', city: 'Recife', state: 'PE', regionId: 7,
  },
  { 
    id: 13, 
    name: 'Camila Lima', 
    email: 'camila@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '85922221111',
    street: 'Av. Beira Mar, 606', neighborhood: 'Meireles', city: 'Fortaleza', state: 'CE', regionId: 8,
  },
  { 
    id: 14, 
    name: 'Gustavo Barbosa', 
    email: 'gustavo@tiao.com', 
    password: '123', 
    role: 'client', 
    isProfileComplete: true,
    phone: '61911110000',
    street: 'SCS Quadra 7, Bloco A', neighborhood: 'Asa Sul', city: 'Brasília', state: 'DF', regionId: 9,
  },
  // --- PROFESSIONALS ---
  { 
    id: 2, 
    name: 'Roberto Carlos', 
    email: 'profissional@tiao.com', 
    password: '123', 
    role: 'professional', 
    status: 'approved', 
    isProfileComplete: true,
    phone: '11912345678',
    street: 'Av. Atlântica, 1702', neighborhood: 'Copacabana', city: 'Rio de Janeiro', state: 'RJ', regionId: 1,
    services: ['Encanador', 'Gesseiro'],
    cpfCnpj: '123.456.789-00',
    bio: 'Mais de 20 anos de experiência em reparos hidráulicos e acabamentos em gesso. Rápido, eficiente e confiável.',
    imageUrl: 'https://picsum.photos/seed/roberto/300/300',
    rating: 4.9,
    reviewsCount: 128,
    reviews: [
      { id: 1, author: 'Ana', rating: 5, comment: 'Resolveu meu vazamento em 10 minutos! Incrível.' },
      { id: 2, author: 'Bruno', rating: 5, comment: 'Muito profissional e educado. Recomendo.' },
    ],
    pricing: { description: 'A partir de R$ 150,00' },
    availability: { 'Seg-Sex': '08:00 - 18:00', 'Sábado': '09:00 - 13:00' },
  },
  { 
    id: 15, 
    name: 'Sérgio Mendes', 
    email: 'sergio@tiao.com', 
    password: '123', 
    role: 'professional', 
    status: 'approved', 
    isProfileComplete: true,
    phone: '21988776655',
    street: 'Rua Conde de Bonfim, 800', neighborhood: 'Tijuca', city: 'Rio de Janeiro', state: 'RJ', regionId: 1,
    services: ['Encanador'],
    cpfCnpj: '222.333.444-55',
    bio: 'Especialista em detecção de vazamentos com equipamentos de ultrassom. Serviço limpo e sem quebra-quebra desnecessário.',
    imageUrl: 'https://picsum.photos/seed/sergio/300/300',
    rating: 4.8,
    reviewsCount: 76,
    pricing: { description: 'Orçamento a combinar' },
  },
  {
    id: 4,
    name: 'Mariana Silva',
    services: ['Eletricista', 'Técnico de TI'],
    email: 'mariana@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '11987654321',
    street: 'Rua Harmonia, 123', neighborhood: 'Vila Madalena', city: 'São Paulo', state: 'SP', regionId: 2,
    cpfCnpj: '098.765.432-11',
    rating: 4.8,
    reviewsCount: 95,
    bio: 'Especialista em instalações elétricas e redes. Segurança e conectividade em primeiro lugar.',
    imageUrl: 'https://picsum.photos/seed/mariana/300/300',
    reviews: [
        { id: 1, author: 'Carlos', rating: 5, comment: 'Trocou toda a fiação do meu apartamento com perfeição.' },
        { id: 2, author: 'Julia', rating: 4, comment: 'Serviço bem feito, mas demorou um pouco para chegar.' },
    ],
    pricing: { description: 'R$ 90,00 por hora' },
    availability: { 'Seg-Sex': '09:00 - 17:00' },
  },
  {
    id: 16,
    name: 'Fábio Lima',
    services: ['Eletricista'],
    email: 'fabio@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '11976543210',
    street: 'Rua Tuiuti, 456', neighborhood: 'Tatuapé', city: 'São Paulo', state: 'SP', regionId: 2,
    cpfCnpj: '333.444.555-66',
    rating: 4.9,
    reviewsCount: 112,
    bio: 'Instalação de lustres, ventiladores de teto e quadros de luz. Atendo emergências 24h.',
    imageUrl: 'https://picsum.photos/seed/fabio/300/300',
    pricing: { description: 'Serviços a partir de R$ 120,00' },
  },
  {
    id: 5,
    name: 'Pedro Pendente',
    email: 'pedro@tiao.com',
    password: '123',
    role: 'professional',
    status: 'pending',
    isProfileComplete: false,
    phone: '31999998888',
    street: 'Av. Getúlio Vargas, 789', neighborhood: 'Savassi', city: 'Belo Horizonte', state: 'MG', regionId: 3,
    services: ['Pintor'],
    cpfCnpj: '111.222.333-44',
  },
  {
    id: 17,
    name: 'Jorge Benício',
    services: ['Pintor', 'Gesseiro'],
    email: 'jorge@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '31988887777',
    street: 'Rua dos Caetés, 101', neighborhood: 'Centro', city: 'Belo Horizonte', state: 'MG', regionId: 3,
    cpfCnpj: '444.555.666-77',
    rating: 4.7,
    reviewsCount: 68,
    bio: 'Pintura residencial e comercial, texturas, grafiato e reparos em gesso. Acabamento de primeira qualidade e limpeza garantida.',
    imageUrl: 'https://picsum.photos/seed/jorge/300/300',
    pricing: { description: 'Orçamento grátis por m²' },
  },
  {
    id: 18,
    name: 'Vanessa da Mata',
    services: ['Pintor'],
    email: 'vanessa@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '21977778888',
    street: 'Av. das Américas, 202', neighborhood: 'Barra da Tijuca', city: 'Rio de Janeiro', state: 'RJ', regionId: 1,
    cpfCnpj: '555.666.777-88',
    rating: 5.0,
    reviewsCount: 45,
    bio: 'Pintura decorativa e artística para ambientes internos. Transformo sua parede em uma obra de arte.',
    imageUrl: 'https://picsum.photos/seed/vanessa/300/300',
    pricing: { description: 'Projetos a partir de R$ 500,00' },
  },
  {
    id: 19,
    name: 'Thiago Segurança',
    services: ['Segurança', 'Chaveiro'],
    email: 'thiago@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '11966665555',
    street: 'Av. Giovanni Gronchi, 303', neighborhood: 'Morumbi', city: 'São Paulo', state: 'SP', regionId: 2,
    cpfCnpj: '666.777.888-99',
    rating: 4.9,
    reviewsCount: 88,
    bio: 'Instalação de câmeras de segurança (CFTV), alarmes, cercas elétricas e serviços de chaveiro 24h.',
    imageUrl: 'https://picsum.photos/seed/thiago/300/300',
    pricing: { description: 'Pacotes de instalação a combinar' },
  },
  {
    id: 20,
    name: 'Paula Toller',
    services: ['Segurança'],
    email: 'paula@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '21955554444',
    street: 'Praia de Botafogo, 404', neighborhood: 'Botafogo', city: 'Rio de Janeiro', state: 'RJ', regionId: 1,
    cpfCnpj: '777.888.999-00',
    rating: 4.8,
    reviewsCount: 52,
    bio: 'Consultoria de segurança residencial e instalação de fechaduras digitais e portões eletrônicos.',
    imageUrl: 'https://picsum.photos/seed/paula/300/300',
    pricing: { description: 'Consulta técnica: R$ 250,00' },
  },
  {
    id: 21,
    name: 'Marcos Freteiro',
    services: ['Fretes', 'Montador de Móveis'],
    email: 'marcos@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '11944443333',
    street: 'Rua Augusta, 505', neighborhood: 'Consolação', city: 'São Paulo', state: 'SP', regionId: 2,
    cpfCnpj: '888.999.000-11',
    rating: 4.7,
    reviewsCount: 150,
    bio: 'Pequenos fretes, mudanças e montagem de móveis com responsabilidade e cuidado.',
    imageUrl: 'https://picsum.photos/seed/marcos/300/300',
    pricing: { description: 'Fretes a partir de R$ 80,00' },
  },
  {
    id: 22,
    name: 'Renata Mudanças',
    services: ['Fretes'],
    email: 'renata@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '41933332222',
    street: 'Av. República Argentina, 606', neighborhood: 'Água Verde', city: 'Curitiba', state: 'PR', regionId: 6,
    cpfCnpj: '999.000.111-22',
    rating: 4.9,
    reviewsCount: 89,
    bio: 'Mudanças residenciais completas com caminhão baú. Equipe para embalagem, desmontagem e montagem de móveis.',
    imageUrl: 'https://picsum.photos/seed/renata/300/300',
    pricing: { description: 'Orçamento sem compromisso' },
  },
  {
    id: 23,
    name: 'Silvio Meira',
    services: ['Técnico de TI'],
    email: 'silvio@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '81922221111',
    street: 'Cais do Apolo, 707', neighborhood: 'Recife Antigo', city: 'Recife', state: 'PE', regionId: 7,
    cpfCnpj: '000.111.222-33',
    rating: 5.0,
    reviewsCount: 210,
    bio: 'Manutenção de computadores e notebooks, remoção de vírus, formatação e instalação de programas. Atendimento em domicílio.',
    imageUrl: 'https://picsum.photos/seed/silvio/300/300',
    pricing: { description: 'Visita técnica: R$ 100,00' },
  },
  {
    id: 24,
    name: 'Débora TI',
    services: ['Técnico de TI'],
    email: 'debora@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '61911112222',
    street: 'CLN 205, Bloco C', neighborhood: 'Asa Norte', city: 'Brasília', state: 'DF', regionId: 9,
    cpfCnpj: '111.222.333-45',
    rating: 4.9,
    reviewsCount: 98,
    bio: 'Configuração de redes Wi-Fi, roteadores e repetidores de sinal. Deixe sua internet voando!',
    imageUrl: 'https://picsum.photos/seed/debora/300/300',
    pricing: { description: 'Configuração de rede: R$ 180,00' },
  },
  // New Professionals
  {
    id: 25,
    name: 'Carlos Marceneiro',
    services: ['Marceneiro', 'Montador de Móveis'],
    email: 'carlos.marceneiro@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '11987651234',
    street: 'Rua dos Pinheiros, 808', neighborhood: 'Pinheiros', city: 'São Paulo', state: 'SP', regionId: 2,
    cpfCnpj: '121.232.343-45',
    rating: 4.8,
    reviewsCount: 65,
    bio: 'Móveis planejados e reparos em madeira. Qualidade e fino acabamento.',
    imageUrl: 'https://picsum.photos/seed/carlos/300/300',
    pricing: { description: 'Orçamento sob consulta' },
  },
  {
    id: 26,
    name: 'Laura Jardineira',
    services: ['Jardineiro'],
    email: 'laura.jardim@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '21988889999',
    street: 'Rua Jardim Botânico, 909', neighborhood: 'Jardim Botânico', city: 'Rio de Janeiro', state: 'RJ', regionId: 1,
    cpfCnpj: '232.343.454-56',
    rating: 4.9,
    reviewsCount: 43,
    bio: 'Paisagismo, manutenção de jardins e controle de pragas de forma orgânica.',
    imageUrl: 'https://picsum.photos/seed/laura/300/300',
    pricing: { description: 'Manutenção a partir de R$ 120,00' },
  },
  {
    id: 27,
    name: 'Fernando Dedetizador',
    services: ['Dedetizador'],
    email: 'fernando.dedetiza@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '31977778888',
    street: 'Av. Afonso Pena, 1010', neighborhood: 'Centro', city: 'Belo Horizonte', state: 'MG', regionId: 3,
    cpfCnpj: '343.454.565-67',
    rating: 4.7,
    reviewsCount: 88,
    bio: 'Controle de pragas urbanas. Ratos, baratas, cupins e formigas. Atendimento rápido.',
    imageUrl: 'https://picsum.photos/seed/fernando/300/300',
    pricing: { description: 'Serviços a partir de R$ 180,00' },
  },
  {
    id: 28,
    name: 'Gisele Vidros',
    services: ['Vidraceiro'],
    email: 'gisele.vidros@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '41966667777',
    street: 'Rua 24 de Maio, 1111', neighborhood: 'Centro', city: 'Curitiba', state: 'PR', regionId: 6,
    cpfCnpj: '454.565.676-78',
    rating: 4.9,
    reviewsCount: 34,
    bio: 'Box para banheiros, espelhos e fechamento de sacadas. Qualidade e segurança.',
    imageUrl: 'https://picsum.photos/seed/gisele/300/300',
    pricing: { description: 'Orçamento sem compromisso' },
  },
  {
    id: 29,
    name: 'Ricardo Ar',
    services: ['Ar Condicionado', 'Eletricista'],
    email: 'ricardo.ar@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '81955556666',
    street: 'Rua da Aurora, 1212', neighborhood: 'Santo Amaro', city: 'Recife', state: 'PE', regionId: 7,
    cpfCnpj: '565.676.787-89',
    rating: 5.0,
    reviewsCount: 115,
    bio: 'Instalação e manutenção de ar condicionado split e de janela. Limpeza e higienização.',
    imageUrl: 'https://picsum.photos/seed/ricardoar/300/300',
    pricing: { description: 'Limpeza a partir de R$ 150,00' },
  },
  {
    id: 30,
    name: 'Mauro Pedreiro',
    services: ['Pedreiro', 'Pintor'],
    email: 'mauro.obra@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '71944445555',
    street: 'Ladeira do Pelourinho, 1313', neighborhood: 'Pelourinho', city: 'Salvador', state: 'BA', regionId: 4,
    cpfCnpj: '676.787.898-90',
    rating: 4.8,
    reviewsCount: 92,
    bio: 'Pequenas reformas, alvenaria, reboco e assentamento de pisos e azulejos.',
    imageUrl: 'https://picsum.photos/seed/mauro/300/300',
    pricing: { description: 'Diária a partir de R$ 200,00' },
  },
  {
    id: 31,
    name: 'Sonia Diarista',
    services: ['Diarista'],
    email: 'sonia.limpeza@tiao.com',
    password: '123',
    role: 'professional',
    status: 'approved',
    isProfileComplete: true,
    phone: '61933334444',
    street: 'Eixo Monumental, 1414', neighborhood: 'Plano Piloto', city: 'Brasília', state: 'DF', regionId: 9,
    cpfCnpj: '787.898.909-01',
    rating: 4.9,
    reviewsCount: 130,
    bio: 'Faxina residencial e comercial. Organização e capricho em cada detalhe.',
    imageUrl: 'https://picsum.photos/seed/sonia/300/300',
    pricing: { description: 'Diária a partir de R$ 160,00' },
  },
];

export const serviceRequests: ServiceRequest[] = [
    {
        id: 101,
        clientId: 1,
        professionalId: 2,
        serviceName: 'Encanador',
        status: 'completed',
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
    },
    {
        id: 102,
        clientId: 6,
        professionalId: 2,
        serviceName: 'Gesseiro',
        status: 'accepted',
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    },
    {
        id: 103,
        clientId: 1,
        professionalId: 4,
        serviceName: 'Eletricista',
        status: 'pending',
        createdAt: new Date().toISOString(), // today
    },
    {
        id: 104,
        clientId: 6,
        professionalId: 2,
        serviceName: 'Encanador',
        status: 'pending',
        createdAt: new Date().toISOString(), // today
    }
];

export const jobPosts: JobPost[] = [
    {
        id: 201,
        clientId: 1, // Ana Cliente
        serviceCategory: 'Eletricista',
        description: 'Preciso instalar 3 novas tomadas na minha sala e trocar o disjuntor do chuveiro. Urgente!',
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    },
    {
        id: 202,
        clientId: 6, // Bruno Cliente
        serviceCategory: 'Encanador',
        description: 'Vazamento pequeno debaixo da pia da cozinha. Acredito que seja o sifão.',
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    },
    {
        id: 203,
        clientId: 7, // Carla Souza
        serviceCategory: 'Pintor',
        description: 'Quero pintar meu quarto de 12m². A cor é um cinza claro, já tenho a tinta.',
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    }
];

export const initialChatMessages: ChatMessage[] = [
    {
        id: 1,
        senderId: 1, // Ana Cliente
        receiverId: 2, // Roberto Carlos
        text: 'Olá Roberto, tudo bem? Vi seu perfil e gostei muito. Você estaria disponível amanhã para ver um vazamento na minha cozinha?',
        timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 minutes ago
    },
    {
        id: 2,
        senderId: 2,
        receiverId: 1,
        text: 'Olá Ana! Tudo ótimo, obrigado. Sim, tenho um horário livre amanhã às 14h. Fica bom pra você?',
        timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    },
];


export const serviceRequestFormFields: Record<string, FormField[]> = {
  'Encanador': [
    { name: 'tipoVazamento', label: 'Qual o tipo de problema?', type: 'select', options: ['Selecione...', 'Torneira pingando', 'Vazamento na parede', 'Vaso sanitário', 'Ralo entupido', 'Outro'] },
    { name: 'urgencia', label: 'Qual a urgência?', type: 'select', options: ['Selecione...', 'Baixa', 'Média', 'Alta - Vazando agora'] }
  ],
  'Eletricista': [
    { name: 'disjuntor', label: 'O problema é no disjuntor?', type: 'select', options: ['Selecione...', 'Sim', 'Não', 'Não sei'] },
    { name: 'local', label: 'Qual o cômodo/local do problema?', type: 'text', placeholder: 'Ex: Chuveiro do banheiro social' }
  ],
  'Pintor': [
      { name: 'area', label: 'Qual a área aproximada a ser pintada (m²)?', type: 'text', placeholder: 'Ex: 25' },
      { name: 'tipo', label: 'Tipo de pintura?', type: 'select', options: ['Selecione...', 'Interna', 'Externa (fachada)', 'Apenas uma parede', 'Móveis'] }
  ],
  'Diarista': [
      { name: 'comodos', label: 'Quantos cômodos?', type: 'text', placeholder: 'Ex: 2 quartos, 1 sala, 1 cozinha, 2 banheiros' },
      { name: 'material', label: 'Material de limpeza incluso?', type: 'select', options: ['Selecione...', 'Sim, por conta do profissional', 'Não, eu forneço o material'] }
  ]
};