import type { ServiceCategory, User, ServiceRequest, FormField } from './types';
import {
  WrenchScrewdriverIcon,
  PaintBrushIcon,
  BoltIcon,
  ComputerDesktopIcon,
  CubeIcon,
  TruckIcon,
  ShieldExclamationIcon,
  UserGroupIcon,
  BuildingStorefrontIcon,
  ChatBubbleBottomCenterTextIcon,
  HomeModernIcon,
  SunIcon,
  BugAntIcon,
  StopIcon,
  SparklesIcon,
  CpuChipIcon,
  RectangleGroupIcon
} from './components/icons';

export const serviceCategories: ServiceCategory[] = [
  { name: 'Encanador', icon: WrenchScrewdriverIcon },
  { name: 'Pintor', icon: PaintBrushIcon },
  { name: 'Eletricista', icon: BoltIcon },
  { name: 'Segurança', icon: ShieldExclamationIcon },
  { name: 'Fretes e Mudanças', icon: TruckIcon },
  { name: 'TI', icon: ComputerDesktopIcon },
  { name: 'Marceneiro', icon: BuildingStorefrontIcon },
  { name: 'Jardineira', icon: SunIcon },
  { name: 'Dedetizador', icon: BugAntIcon },
  { name: 'Vidros', icon: RectangleGroupIcon },
  { name: 'Ar', icon: CpuChipIcon },
  { name: 'Pedreiro', icon: HomeModernIcon },
  { name: 'Diarista', icon: SparklesIcon },
  { name: 'Montador de Móveis', icon: CubeIcon },
  
];

export const mockUsers: User[] = [
  // Admin
  {
    id: 1,
    email: 'admin@tiao.com',
    password: 'admin',
    name: 'Admin Tião',
    role: 'admin',
    phone: '11999999999',
    street: 'Rua da Administração, 1',
    neighborhood: 'Centro',
    city: 'São Paulo',
    state: 'SP',
    regionId: 1,
    isProfileComplete: true,
    transactions: [],
  },
  // Clients
  {
    id: 201,
    email: 'cliente@tiao.com',
    password: 'client',
    name: 'Ana Cliente',
    role: 'client',
    phone: '11988881111',
    street: 'Rua do Cliente Fiel, 10',
    neighborhood: 'Moema',
    city: 'São Paulo',
    state: 'SP',
    regionId: 1,
    isProfileComplete: true,
    walletBalanceTC: 150,
    transactions: [],
  },
  {
    id: 202,
    email: 'bruno@tiao.com',
    password: 'client',
    name: 'Bruno Cliente',
    role: 'client',
    phone: '21988882222',
    street: 'Avenida Atlântica, 20',
    neighborhood: 'Copacabana',
    city: 'Rio de Janeiro',
    state: 'RJ',
    regionId: 2,
    isProfileComplete: true,
    walletBalanceTC: 50,
    transactions: [],
  },
  {
    id: 203,
    email: 'carla@tiao.com',
    password: 'client',
    name: 'Carla Souza',
    role: 'client',
    phone: '31988883333',
    street: 'Rua da Bahia, 30',
    neighborhood: 'Lourdes',
    city: 'Belo Horizonte',
    state: 'MG',
    regionId: 3,
    isProfileComplete: true,
    walletBalanceTC: 0,
    transactions: [],
  },
    { id: 204, email: 'lucas@tiao.com', password: 'client', name: 'Lucas Pereira', role: 'client', phone: '11911112222', street: 'Rua Augusta, 100', neighborhood: 'Consolação', city: 'São Paulo', state: 'SP', regionId: 1, isProfileComplete: true, walletBalanceTC: 25, transactions: [], },
    { id: 205, email: 'juliana@tiao.com', password: 'client', name: 'Juliana Costa', role: 'client', phone: '21922223333', street: 'Rua Visconde de Pirajá, 200', neighborhood: 'Ipanema', city: 'Rio de Janeiro', state: 'RJ', regionId: 2, isProfileComplete: true, walletBalanceTC: 0, transactions: [], },
    { id: 206, email: 'fernando@tiao.com', password: 'client', name: 'Fernando Martins', role: 'client', phone: '31933334444', street: 'Avenida Afonso Pena, 300', neighborhood: 'Centro', city: 'Belo Horizonte', state: 'MG', regionId: 3, isProfileComplete: true, walletBalanceTC: 0, transactions: [], },
    { id: 207, email: 'beatriz@tiao.com', password: 'client', name: 'Beatriz Almeida', role: 'client', phone: '11944445555', street: 'Avenida Paulista, 400', neighborhood: 'Bela Vista', city: 'São Paulo', state: 'SP', regionId: 1, isProfileComplete: true, walletBalanceTC: 100, transactions: [], },
    { id: 208, email: 'ricardo@tiao.com', password: 'client', name: 'Ricardo Rocha', role: 'client', phone: '21955556666', street: 'Rua Farme de Amoedo, 500', neighborhood: 'Ipanema', city: 'Rio de Janeiro', state: 'RJ', regionId: 2, isProfileComplete: true, walletBalanceTC: 0, transactions: [], },
    { id: 209, email: 'camila@tiao.com', password: 'client', name: 'Camila Lima', role: 'client', phone: '31966667777', street: 'Rua dos Timbiras, 600', neighborhood: 'Funcionários', city: 'Belo Horizonte', state: 'MG', regionId: 3, isProfileComplete: true, walletBalanceTC: 75, transactions: [], },
    { id: 210, email: 'gustavo@tiao.com', password: 'client', name: 'Gustavo Barbosa', role: 'client', phone: '11977778888', street: 'Rua Oscar Freire, 700', neighborhood: 'Jardins', city: 'São Paulo', state: 'SP', regionId: 1, isProfileComplete: true, walletBalanceTC: 0, transactions: [], },
  // Professionals - Approved
  {
    id: 101,
    email: 'profissional@tiao.com',
    password: 'prof',
    name: 'Roberto Carlos',
    role: 'professional',
    phone: '11912345678',
    street: 'Rua dos Encanadores, 10',
    neighborhood: 'Moema',
    city: 'São Paulo',
    state: 'SP',
    regionId: 1,
    isProfileComplete: true,
    status: 'approved',
    services: ['Encanador', 'Pedreiro'],
    cpfCnpj: '111.111.111-11',
    bio: 'Rei dos reparos hidráulicos. Mais de 30 anos de experiência.',
    imageUrl: 'https://i.pravatar.cc/300?u=101',
    rating: 4.9,
    reviewsCount: 150,
    pricing: { description: 'Orçamento detalhado' },
    walletBalanceTC: 3200,
    transactions: [],
  },
  { id: 102, email: 'sergio@tiao.com', password: 'prof', name: 'Sérgio Mendes', role: 'professional', phone: '21923456789', street: 'Rua das Tintas, 20', neighborhood: 'Copacabana', city: 'Rio de Janeiro', state: 'RJ', regionId: 2, isProfileComplete: true, status: 'approved', services: ['Pintor'], cpfCnpj: '222.222.222-22', bio: 'Pintura fina com a bossa do Rio.', imageUrl: 'https://i.pravatar.cc/300?u=102', rating: 4.8, reviewsCount: 88, pricing: { description: 'A partir de R$ 30/m²' }, walletBalanceTC: 4500, transactions: [], },
  { id: 103, email: 'mariana@tiao.com', password: 'prof', name: 'Mariana Silva', role: 'professional', phone: '31934567890', street: 'Rua dos Eletricistas, 30', neighborhood: 'Savassi', city: 'Belo Horizonte', state: 'MG', regionId: 3, isProfileComplete: true, status: 'approved', services: ['Eletricista'], cpfCnpj: '333.333.333-33', bio: 'Soluções elétricas seguras e eficientes.', imageUrl: 'https://i.pravatar.cc/300?u=103', rating: 4.9, reviewsCount: 120, pricing: { description: 'Visita técnica R$ 70' }, walletBalanceTC: 1800, transactions: [], },
  { id: 104, email: 'fabio@tiao.com', password: 'prof', name: 'Fábio Lima', role: 'professional', phone: '11945678901', street: 'Rua dos Móveis, 40', neighborhood: 'Pinheiros', city: 'São Paulo', state: 'SP', regionId: 1, isProfileComplete: true, status: 'approved', services: ['Montador de Móveis'], cpfCnpj: '444.444.444-44', bio: 'Montagem e desmontagem com precisão.', imageUrl: 'https://i.pravatar.cc/300?u=104', rating: 4.7, reviewsCount: 95, pricing: { description: 'A partir de R$ 80' }, walletBalanceTC: 950, transactions: [], },
  { id: 105, email: 'jorge@tiao.com', password: 'prof', name: 'Jorge Benício', role: 'professional', phone: '21956789012', street: 'Rua da Marcenaria, 50', neighborhood: 'Lapa', city: 'Rio de Janeiro', state: 'RJ', regionId: 2, isProfileComplete: true, status: 'approved', services: ['Marceneiro'], cpfCnpj: '555.555.555-55', bio: 'Móveis planejados com a beleza do samba.', imageUrl: 'https://i.pravatar.cc/300?u=105', rating: 5.0, reviewsCount: 200, pricing: { description: 'Orçamento sob medida' }, walletBalanceTC: 7300, transactions: [], },
  { id: 106, email: 'vanessa@tiao.com', password: 'prof', name: 'Vanessa da Mata', role: 'professional', phone: '31967890123', street: 'Alameda das Flores, 60', neighborhood: 'Pampulha', city: 'Belo Horizonte', state: 'MG', regionId: 3, isProfileComplete: true, status: 'approved', services: ['Jardineira'], cpfCnpj: '666.666.666-66', bio: 'Cuido do seu jardim com muito amor e carinho.', imageUrl: 'https://i.pravatar.cc/300?u=106', rating: 4.9, reviewsCount: 75, pricing: { description: 'Manutenção a partir de R$ 150' }, walletBalanceTC: 1200, transactions: [], },
  { id: 107, email: 'thiago@tiao.com', password: 'prof', name: 'Thiago Segurança', role: 'professional', phone: '11978901234', street: 'Rua da Proteção, 70', neighborhood: 'Tatuapé', city: 'São Paulo', state: 'SP', regionId: 1, isProfileComplete: true, status: 'approved', services: ['Segurança'], cpfCnpj: '777.777.777-77', bio: 'Instalação de câmeras e alarmes.', imageUrl: 'https://i.pravatar.cc/300?u=107', rating: 4.8, reviewsCount: 50, pricing: { description: 'Consulte nossos pacotes' }, walletBalanceTC: 2100, transactions: [], },
  { id: 108, email: 'paula@tiao.com', password: 'prof', name: 'Paula Toller', role: 'professional', phone: '21989012345', street: 'Avenida do Vidro, 80', neighborhood: 'Botafogo', city: 'Rio de Janeiro', state: 'RJ', regionId: 2, isProfileComplete: true, status: 'approved', services: ['Vidros'], cpfCnpj: '888.888.888-88', bio: 'Vidros e espelhos com um toque de rock.', imageUrl: 'https://i.pravatar.cc/300?u=108', rating: 4.7, reviewsCount: 60, pricing: { description: 'Orçamento gratuito' }, walletBalanceTC: 1500, transactions: [], },
  { id: 109, email: 'marcos@tiao.com', password: 'prof', name: 'Marcos Freteiro', role: 'professional', phone: '31990123456', street: 'Rua das Cargas, 90', neighborhood: 'Carlos Prates', city: 'Belo Horizonte', state: 'MG', regionId: 3, isProfileComplete: true, status: 'approved', services: ['Fretes e Mudanças'], cpfCnpj: '999.999.999-99', bio: 'Levo tudo com cuidado e segurança.', imageUrl: 'https://i.pravatar.cc/300?u=109', rating: 4.6, reviewsCount: 110, pricing: { description: 'Fretes a partir de R$ 100' }, walletBalanceTC: 800, transactions: [], },
  { id: 110, email: 'renata@tiao.com', password: 'prof', name: 'Renata Mudanças', role: 'professional', phone: '11901234567', street: 'Rua das Caixas, 100', neighborhood: 'Vila Madalena', city: 'São Paulo', state: 'SP', regionId: 1, isProfileComplete: true, status: 'approved', services: ['Fretes e Mudanças'], cpfCnpj: '101.010.101-01', bio: 'Organização e agilidade para sua mudança.', imageUrl: 'https://i.pravatar.cc/300?u=110', rating: 4.9, reviewsCount: 80, pricing: { description: 'Mudanças completas' }, walletBalanceTC: 2500, transactions: [], },
  { id: 111, email: 'silvio@tiao.com', password: 'prof', name: 'Silvio Meira', role: 'professional', phone: '21912345678', street: 'Rua do Ar Condicionado, 110', neighborhood: 'Flamengo', city: 'Rio de Janeiro', state: 'RJ', regionId: 2, isProfileComplete: true, status: 'approved', services: ['Ar'], cpfCnpj: '121.212.121-21', bio: 'Instalação e manutenção de ar condicionado.', imageUrl: 'https://i.pravatar.cc/300?u=111', rating: 4.8, reviewsCount: 90, pricing: { description: 'Limpeza a partir de R$ 120' }, walletBalanceTC: 1750, transactions: [], },
  { id: 112, email: 'debora@tiao.com', password: 'prof', name: 'Débora TI', role: 'professional', phone: '31923456789', street: 'Rua dos Computadores, 120', neighborhood: 'Centro', city: 'Belo Horizonte', state: 'MG', regionId: 3, isProfileComplete: true, status: 'approved', services: ['TI'], cpfCnpj: '131.313.131-31', bio: 'Suporte técnico para pessoas e empresas.', imageUrl: 'https://i.pravatar.cc/300?u=112', rating: 5.0, reviewsCount: 130, pricing: { description: 'Visita R$ 90' }, walletBalanceTC: 3100, transactions: [], },
  { id: 113, email: 'carlos.marceneiro@tiao.com', password: 'prof', name: 'Carlos Marceneiro', role: 'professional', phone: '11934567890', street: 'Rua da Madeira, 130', neighborhood: 'Lapa', city: 'São Paulo', state: 'SP', regionId: 1, isProfileComplete: true, status: 'approved', services: ['Marceneiro'], cpfCnpj: '141.414.141-41', bio: 'Móveis sob medida com acabamento perfeito.', imageUrl: 'https://i.pravatar.cc/300?u=113', rating: 4.9, reviewsCount: 100, pricing: { description: 'Solicite seu orçamento' }, walletBalanceTC: 5200, transactions: [], },
  { id: 114, email: 'laura.jardim@tiao.com', password: 'prof', name: 'Laura Jardineira', role: 'professional', phone: '21945678901', street: 'Rua das Plantas, 140', neighborhood: 'Jardim Botânico', city: 'Rio de Janeiro', state: 'RJ', regionId: 2, isProfileComplete: true, status: 'approved', services: ['Jardineira'], cpfCnpj: '151.515.151-51', bio: 'Paisagismo e manutenção de jardins.', imageUrl: 'https://i.pravatar.cc/300?u=114', rating: 4.8, reviewsCount: 65, pricing: { description: 'Projetos personalizados' }, walletBalanceTC: 1900, transactions: [], },
  { id: 115, email: 'fernando.dedetiza@tiao.com', password: 'prof', name: 'Fernando Dedetizador', role: 'professional', phone: '31956789012', street: 'Rua dos Insetos, 150', neighborhood: 'Floresta', city: 'Belo Horizonte', state: 'MG', regionId: 3, isProfileComplete: true, status: 'approved', services: ['Dedetizador'], cpfCnpj: '161.616.161-61', bio: 'Controle de pragas com segurança.', imageUrl: 'https://i.pravatar.cc/300?u=115', rating: 4.7, reviewsCount: 45, pricing: { description: 'A partir de R$ 200' }, walletBalanceTC: 1100, transactions: [], },
  { id: 116, email: 'gisele.vidros@tiao.com', password: 'prof', name: 'Gisele Vidros', role: 'professional', phone: '11967890123', street: 'Rua do Reflexo, 160', neighborhood: 'Mooca', city: 'São Paulo', state: 'SP', regionId: 1, isProfileComplete: true, status: 'approved', services: ['Vidros'], cpfCnpj: '171.717.171-71', bio: 'Boxes, espelhos e fechamento de varandas.', imageUrl: 'https://i.pravatar.cc/300?u=116', rating: 4.9, reviewsCount: 85, pricing: { description: 'Orçamento rápido' }, walletBalanceTC: 2800, transactions: [], },
  { id: 117, email: 'ricardo.ar@tiao.com', password: 'prof', name: 'Ricardo Ar', role: 'professional', phone: '21978901234', street: 'Rua da Brisa, 170', neighborhood: 'Tijuca', city: 'Rio de Janeiro', state: 'RJ', regionId: 2, isProfileComplete: true, status: 'approved', services: ['Ar'], cpfCnpj: '181.818.181-81', bio: 'Climatização de ambientes residenciais e comerciais.', imageUrl: 'https://i.pravatar.cc/300?u=117', rating: 4.8, reviewsCount: 70, pricing: { description: 'Instalação e manutenção' }, walletBalanceTC: 1600, transactions: [], },
  { id: 118, email: 'mauro.obra@tiao.com', password: 'prof', name: 'Mauro Pedreiro', role: 'professional', phone: '31989012345', street: 'Rua da Construção, 180', neighborhood: 'Gutierrez', city: 'Belo Horizonte', state: 'MG', regionId: 3, isProfileComplete: true, status: 'approved', services: ['Pedreiro', 'Pintor'], cpfCnpj: '191.919.191-91', bio: 'Do alicerce ao acabamento.', imageUrl: 'https://i.pravatar.cc/300?u=118', rating: 4.7, reviewsCount: 140, pricing: { description: 'Construção e reforma' }, walletBalanceTC: 6500, transactions: [], },
  { id: 119, email: 'sonia.limpeza@tiao.com', password: 'prof', name: 'Sonia Diarista', role: 'professional', phone: '11990123456', street: 'Rua do Brilho, 190', neighborhood: 'Perdizes', city: 'São Paulo', state: 'SP', regionId: 1, isProfileComplete: true, status: 'approved', services: ['Diarista'], cpfCnpj: '202.020.202-02', bio: 'Limpeza e organização que transformam seu lar.', imageUrl: 'https://i.pravatar.cc/300?u=119', rating: 5.0, reviewsCount: 250, pricing: { description: 'Diarista a partir de R$ 180' }, walletBalanceTC: 900, transactions: [], },
  // Professionals - Pending
  {
    id: 120,
    email: 'pedro@tiao.com',
    password: 'prof',
    name: 'Pedro Pendente',
    role: 'professional',
    phone: '11999990000',
    street: 'Rua da Análise, 200',
    neighborhood: 'Centro',
    city: 'São Paulo',
    state: 'SP',
    regionId: 1,
    isProfileComplete: true,
    status: 'pending',
    services: ['Encanador'],
    cpfCnpj: '212.121.212-12',
    bio: 'Aguardando aprovação para começar a trabalhar.',
    imageUrl: 'https://i.pravatar.cc/300?u=120',
    rating: 0,
    reviewsCount: 0,
    walletBalanceTC: 0,
    transactions: [],
  },
];

export const mockServiceRequests: ServiceRequest[] = [
    {
        id: 1,
        clientId: 201,
        professionalId: 101,
        service: 'Encanador',
        description: 'Vazamento na pia da cozinha. Urgente!',
        preferredDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
        preferredPeriod: 'Manhã',
        dynamicFields: { problem_type: 'Vazamento', location: 'Pia da cozinha'},
        status: 'awaiting_payment',
        createdAt: new Date(Date.now() - 3600 * 1000 * 5).toISOString(),
        price: 120,
    },
    {
        id: 2,
        clientId: 202,
        professionalId: 102,
        service: 'Pintor',
        description: 'Pintar a sala de estar, cor branca.',
        preferredDate: new Date(Date.now() + 86400000 * 5).toISOString().split('T')[0],
        preferredPeriod: 'Tarde',
        dynamicFields: { area_size: '30', surface_type: 'Parede interna' },
        status: 'completed',
        createdAt: new Date(Date.now() - 86400 * 1000 * 3).toISOString(),
        price: 450,
    },
    {
        id: 3,
        clientId: 201,
        professionalId: 103,
        service: 'Eletricista',
        description: 'Trocar a resistência do chuveiro.',
        preferredDate: new Date(Date.now() + 86400000 * 1).toISOString().split('T')[0],
        preferredPeriod: 'Manhã',
        dynamicFields: { service_type: 'Instalação de chuveiro', urgency: 'Alta' },
        status: 'paid',
        createdAt: new Date(Date.now() - 86400 * 1000 * 7).toISOString(),
        price: 90,
    },
];

export const serviceRequestFormFields: Record<string, FormField[]> = {
    'Encanador': [
        { name: 'problem_type', label: 'Tipo de Problema', type: 'select', options: ['Vazamento', 'Entupimento', 'Instalação', 'Outro'] },
        { name: 'location', label: 'Local do Problema', type: 'text', placeholder: 'Ex: Pia da cozinha, Vaso sanitário' }
    ],
    'Eletricista': [
        { name: 'service_type', label: 'Tipo de Serviço', type: 'select', options: ['Troca de fiação', 'Instalação de tomada', 'Instalação de chuveiro', 'Curto-circuito', 'Outro'] },
        { name: 'urgency', label: 'Urgência', type: 'select', options: ['Alta', 'Média', 'Baixa'] }
    ],
    'Pintor': [
        { name: 'area_size', label: 'Tamanho da Área (m²)', type: 'text', placeholder: 'Ex: 30' },
        { name: 'surface_type', label: 'Tipo de Superfície', type: 'select', options: ['Parede interna', 'Parede externa', 'Teto', 'Portas e Janelas'] }
    ],
    'Montador de Móveis': [
        { name: 'furniture_type', label: 'Tipo de Móvel', type: 'text', placeholder: 'Ex: Guarda-roupa 6 portas, Mesa de jantar' },
        { name: 'has_manual', label: 'Possui o manual de instruções?', type: 'select', options: ['Sim', 'Não'] }
    ],
    // Adding more specific fields for new categories
    'Diarista': [
        { name: 'property_type', label: 'Tipo de Imóvel', type: 'select', options: ['Apartamento', 'Casa', 'Escritório'] },
        { name: 'cleaning_type', label: 'Tipo de Limpeza', type: 'select', options: ['Padrão', 'Pesada', 'Pós-obra'] }
    ],
    'TI': [
        { name: 'device_type', label: 'Tipo de Dispositivo', type: 'select', options: ['Computador/Notebook', 'Celular/Tablet', 'Impressora', 'Rede/Wi-Fi'] },
        { name: 'problem_summary', label: 'Resumo do Problema', type: 'text', placeholder: 'Ex: Computador não liga, Wi-Fi lento' }
    ],
};
